### PR TITLE
Convert to proper helm charts

### PR DESCRIPTION
**Pull request by mhjacks**
I still need to work through the yq scripts and details of the workflow, but here's the essence of the obsoletion of the cmp in IE so far.

### CODE REVIEW

**Comment by mhjacks** [comment]
This PR completely removes the need for the Config Management Plugin for ArgoCD. It does this by refactoring the pipelines, manuela-test, and manuela stormshift applications to operate using helm value files instead of kustomizations. (The same fundamental approach is used - the pipelines edit the override values files in place instead of editing the kustomizations and imagestreams).

As it currently stands, the imagestreams will present two tags - the original (bootstrap) and the current override. Previously, the IS editor would keep up to 5 images in the IS object. That's still very possible, but I think adds some unneeded complexity to the deployment.

The overrides currently include a flag to indicate whether the image has been updated, and a current tag pointer (which is updated by the pipeline task `gitops-imagetag.yaml`. This task edits the override values.

In this process I also updated the task to use yq v4 instead of yq v3 as the previous version did. (I got permissions errors in testing when using the in-place edit option, which is why I do explicit `mv`'s of the values files.

**Comment by mhjacks** [comment]
This batch of changes restores the "list of tags" functionality from kustomize, and includes a pruning task that will limit the number of images in any one imagestream to 5.

**Review by claudiol — APPROVED** [review]
This all looks good to me.  Thank you for doing this. Approved.

**Pull request merged**
